return {
	"bin/autocrop.lua",
	"etc/autocrop/conf.lua",
	"etc/autocrop/program/autoTier.lua",
	"etc/autocrop/program/spread.lua",
	"etc/autocrop/program/stat.lua",
	"lib/autocrop/action.lua",
	"lib/autocrop/config.lua",
	"lib/autocrop/database.lua",
	"lib/autocrop/gps.lua",
	"lib/autocrop/manager.lua",
	"lib/autocrop/plot.lua",
	"lib/autocrop/posUtil.lua",
	"lib/autocrop/scanner.lua",
	"lib/autocrop/signal.lua",
	"lib/autocrop/workingfarm.lua",
}